version: '3.8'

services:
  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - neoconcept-network
    restart: unless-stopped

  backend:
    build: ../backend
    environment:
      - NODE_ENV=production
    networks:
      - neoconcept-network
    restart: unless-stopped

networks:
  neoconcept-network:
    driver: bridge
